# syntax=docker/dockerfile:1

FROM gradle:7.0.2-jdk8 AS build

COPY --chown=gradle:gradle . /buildDir

WORKDIR /buildDir
RUN gradle :webapp:build --no-daemon

FROM openjdk:8-jre-slim

EXPOSE 8080

RUN mkdir /app

COPY --from=build /buildDir/build/libs/*.jar /app/web-app.jar

ENTRYPOINT ["java", "-jar", "/app/web-app.jar"]
