# syntax=docker/dockerfile:1

FROM gradle:7.0.2-jdk16 AS build

COPY --chown=gradle:gradle . /buildDir

WORKDIR /buildDir
RUN gradle :trip-api:build --no-daemon

FROM openjdk:16-jdk-slim

EXPOSE 8084

RUN mkdir /app

COPY --from=build /buildDir/applications/trip-api/build/libs/*.jar /app/trip-api.jar

ENTRYPOINT ["java", "-jar", "/app/trip-api.jar"]
