version: '3.9'
services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile-webapp
    ports:
      - "8080:8080"
    restart: always
  user-api:
    build:
      context: ./
      dockerfile: Dockerfile-user-api
    ports:
      - "8081:8081"
    restart: always
  gps-api:
    build:
      context: ./
      dockerfile: Dockerfile-user-api
    ports:
      - "8082:8082"
    restart: always
  reward-api:
    build:
      context: ./
      dockerfile: Dockerfile-user-api
    ports:
      - "8083:8083"
    restart: always
  trip-api:
    build:
      context: ./
      dockerfile: Dockerfile-user-api
    ports:
      - "8084:8084"
    restart: always
  tracker-api:
    build:
      context: ./
      dockerfile: Dockerfile-user-api
    ports:
      - "8085:8085"
    restart: always