# syntax=docker/dockerfile:1

FROM gradle:7.0.2-jdk16 AS build

COPY --chown=gradle:gradle . /buildDir

WORKDIR /buildDir
RUN gradle :tracker-api:build --no-daemon

FROM openjdk:16-jdk-slim

EXPOSE 8085

RUN mkdir /app

COPY --from=build /buildDir/applications/tracker-api/build/libs/*.jar /app/tracker-api.jar

ENTRYPOINT ["java", "-jar", "/app/tracker-api.jar"]
