# syntax=docker/dockerfile:1

FROM gradle:7.0.2-jdk16 AS build

COPY --chown=gradle:gradle . /buildDir

WORKDIR /buildDir
RUN gradle :reward-api:build --no-daemon

FROM openjdk:16-jdk-slim

EXPOSE 8083

RUN mkdir /app

COPY --from=build /buildDir/applications/reward-api/build/libs/*.jar /app/reward-api.jar

ENTRYPOINT ["java", "-jar", "/app/reward-api.jar"]
