# syntax=docker/dockerfile:1

FROM gradle:7.0.2-jdk16 AS build

COPY --chown=gradle:gradle . /buildDir

WORKDIR /buildDir
RUN gradle :user-api:build --no-daemon

FROM openjdk:16-jdk-slim

EXPOSE 8081

RUN mkdir /app

COPY --from=build /buildDir/applications/user-api/build/libs/*.jar /app/user-api.jar

ENTRYPOINT ["java", "-jar", "/app/user-api.jar"]
