version: '3.9'

networks:
  backend-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  user-api:
    build:
      context: ./
      dockerfile: Dockerfile-user-api
    ports:
      - "8081:8081"
    networks:
      backend-network:
        ipv4_address: 172.20.0.10
  gps-api:
    build:
      context: ./
      dockerfile: Dockerfile-gps-api
    ports:
      - "8082:8082"
    networks:
      backend-network:
        ipv4_address: 172.20.0.2
  reward-api:
    build:
      context: ./
      dockerfile: Dockerfile-reward-api
    ports:
      - "8083:8083"
    networks:
      backend-network:
        ipv4_address: 172.20.0.3
  trip-api:
    build:
      context: ./
      dockerfile: Dockerfile-trip-api
    ports:
      - "8084:8084"
    networks:
      backend-network:
        ipv4_address: 172.20.0.4
  tracker-api:
    depends_on:
      - gps-api
      - reward-api
      - user-api
    build:
      context: ./
      dockerfile: Dockerfile-tracker-api
    ports:
      - "8085:8085"
    networks:
      backend-network:
        ipv4_address: 172.20.0.5
  webapp:
    depends_on:
      - gps-api
      - reward-api
      - user-api
      - trip-api
    build:
      context: ./
      dockerfile: Dockerfile-webapp
    ports:
      - "8080:8080"
    networks:
      backend-network:
        ipv4_address: 172.20.0.6